################################################################################# 
# Author:FS
# Date: 2021
# Copyright: Agustin Bassi (https://github.com/agustinBassi/mq-connection)
# License: MIT
# Project: MQTT Hub
# Brief: These containers act as a MQTT Hub for HBD Final Project.
#
# How to test the MQTT connection to and from the broker:
#
#   - docker exec -it mosquitto mosquitto_sub -t "#"
#   - docker exec -it mosquitto mosquitto_pub -t "/test/topic" -m "Test message"
#
#################################################################################
  
version: '3'

services:

  mosquitto:
    image:                  eclipse-mosquitto:latest
    hostname:               mosquitto
    container_name:         mosquitto

    volumes:
      -                     ./mqtt-broker/config:/mosquitto/config
      -                     ./mqtt-broker/auth:/etc/mosquitto/

    networks:
      -                     mqtt-host-network 
    expose:
      -                     "1883"
      -                     "8883"
      -                     "9001"
    ports:
      -                     "1883:1883"
      -                     "8883:8883"
      -                     "9001:9001"

  node-red:
    depends_on:             
      -                      mosquitto

    image:                   nodered/node-red:latest

    environment:
      -                      TZ=America/Argentina/Buenos_Aires  
    volumes:
      -                      ./node-red:/data
    networks:
      -                      mqtt-host-network 
    ports:
      -                      "1880:1880"

  postgres:
    depends_on:             
      -                      mosquitto
    
    container_name:          postgres

    image:                   postgres:latest # use latest official postgres version
    
    environment:
      POSTGRES_DB:           HBD  
      POSTGRES_USER:         postgres                                     
      POSTGRES_PASSWORD:     12345
      TZ:                    America/Argentina/Buenos_Aires  

    volumes:
      -                     ./db/dumps:/docker-entrypoint-initdb.d
      -                     ./db/data :/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
      -                      postgres-network   
    ports:  
      -                      "5432:5432"

  pgAdmin:
    
    depends_on:             
      -                      postgres
    
    image:                   dpage/pgadmin4:latest
    
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: 12345
      PGADMIN_LISTEN_PORT:   5050
        
    ports:
      -                       "5050:5050"
      
networks:
  
  mqtt-host-network:
    driver:                  bridge

  postgres-network:
    driver:                  bridge
