#################################################################################
# Author:FS
# Date: 2021
# Copyright: Agustin Bassi (https://github.com/agustinBassi/mq-connection)
# License: MIT
# Project: MQTT Broker
# Brief: These containers act as a MQTT broker for HBD Final Project.
#
# How to test the MQTT connection to and from the broker:
#
#   - docker exec -it mosquitto mosquitto_sub -t "#"
#   - docker exec -it mosquitto mosquitto_pub -t "/test/topic" -m "Test message"
#
#################################################################################

version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: mosquitto
    container_name: mosquitto

    volumes:
      - ./mqtt-broker/config:/mosquitto/config
      - ./mqtt-broker/log:/mosquitto/log
      - ./mqtt-broker/auth:/mosquitto/auth

    networks:
      - mqtt-host-network
    expose:
      - "1883"
      - "8883"
      - "9001"
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    restart: unless-stopped

  node-red:
    depends_on:
      - mosquitto

    image: nodered/node-red:latest-12

    user: "1000"

    environment:
      - TZ=America/Argentina/Buenos Aires
    volumes:
      - ./node-red:/data
    networks:
      - mqtt-host-network
    ports:
      - "1880:1880"

networks:
  mqtt-host-network:
    driver: bridge
